nelmio_api_doc:
    documentation:
        info:
            title: API escolar
            description: API com alguns endpoints com o intuito de aprender!
            version: 1.0.0
    areas: 
        path_patterns:
            - ^/api(?!/v1$|(/v1/doc.json$))
